run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - gosec
    - bodyclose
    - nilerr
    - makezero
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - revive

linters-settings:
  govet:
    enable-all: true
  gosec:
    includes:
      - G101
      - G102
      - G103
      - G104
      - G106
      - G107
      - G108
      - G109
      - G110
      - G111
      - G112
      - G113
      - G114
      - G201
      - G202
      - G203
      - G204
      - G301
      - G302
      - G303
      - G304
      - G305
      - G306
      - G307
      - G401
      - G402
      - G403
      - G404
      - G501
      - G502
      - G503
      - G504
      - G505
      - G601
  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: time-naming
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
