name: "Feature Request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma melhoria para a plataforma!
  - type: textarea
    id: problem
    attributes:
      label: O seu pedido de funcionalidade está relacionado a um problema?
      description: Uma descrição clara e concisa do problema (ex. "Fico sempre frustrado quando...")
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Uma descrição clara e concisa do que você deseja que aconteça.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Descreva quaisquer soluções ou funcionalidades alternativas que você tenha considerado.
    validations:
      required: false
